### ISSUE TITLE
Original dictionary.pot

### ISSUE THREAD

**Issue by Idescap** [webalternative/DirectAdmin-Evolution-FR#2]
Hello
Il semple que le fichier dictionary.pot original a changer depuis que tu as commencé la traduction.
Peux-tu uploder le fichier d'où tu es parti que l'on puisse suivre les changements car il y a des traductions qui manquent et on trouve plusieurs autres modifications.
A+

**Comment by WorkingClassKid** [comment]
Bonjour,
 j'ai ajouté le fichier dictionary.pot pour la version 1.54.1 de DA  (version du skin 57d79f90beecb6976abc42a577f661ef16016738)

j'ai aussi mis-à-jour le fichier fr.po pour le dictionary.pot de DA 1.54.1 (version du skin 57d79f90beecb6976abc42a577f661ef16016738)

Cordialement,
